In [ ]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

In [ ]:
import os
os.getcwd()

'/Users/leahmcgovern/BENV0091 Energy Data Analysis/Final Project/Datasets Raw'

In [ ]:
NG_SAP_Hourly_Raw = pd.read_csv('/Users/leahmcgovern/BENV0091 Energy Data Analysis/Final Project/Datasets Raw/NG_SAPhourlyactual_01-04-2021_01-04-2025.csv')

In [ ]:
NG_SAP_Hourly_Raw.head()

,Applicable At,Applicable For,Data Item,Value,Generated Time,Quality Indicator
0,01/04/2025 21:02:20,01/04/2025,"SAP, hourly actual",3.3795,02/04/2025 09:45:05,NaN
1,01/04/2025 20:05:34,01/04/2025,"SAP, hourly actual",3.3701,02/04/2025 09:45:05,NaN
2,01/04/2025 19:03:06,01/04/2025,"SAP, hourly actual",3.3656,02/04/2025 09:45:05,NaN
3,01/04/2025 18:02:11,01/04/2025,"SAP, hourly actual",3.3606,02/04/2025 09:45:05,NaN
4,01/04/2025 17:03:05,01/04/2025,"SAP, hourly actual",3.3574,02/04/2025 09:45:05,NaN

In [ ]:
NG_SAP_Hourly_Clean = NG_SAP_Hourly_Raw.rename(columns={'Applicable At': 'Data Created',
                  'Applicable For': 'Gas Day', 'Data Item': 'Label','Value':'Value (£/MWh)'},inplace=False)
NG_SAP_Hourly_Clean

,Data Created,Gas Day,Label,Value (£/MWh),Generated Time,Quality Indicator
0,01/04/2025 21:02:20,01/04/2025,"SAP, hourly actual",3.3795,02/04/2025 09:45:05,NaN
1,01/04/2025 20:05:34,01/04/2025,"SAP, hourly actual",3.3701,02/04/2025 09:45:05,NaN
2,01/04/2025 19:03:06,01/04/2025,"SAP, hourly actual",3.3656,02/04/2025 09:45:05,NaN
3,01/04/2025 18:02:11,01/04/2025,"SAP, hourly actual",3.3606,02/04/2025 09:45:05,NaN
4,01/04/2025 17:03:05,01/04/2025,"SAP, hourly actual",3.3574,02/04/2025 09:45:05,NaN
...,...,...,...,...,...,...
32058,01/04/2021 05:06:13,01/04/2021,"SAP, hourly actual",1.6532,02/04/2021 09:30:02,NaN
32059,01/04/2021 04:02:38,01/04/2021,"SAP, hourly actual",1.6532,02/04/2021 09:30:02,NaN
32060,01/04/2021 02:01:18,01/04/2021,"SAP, hourly actual",1.6532,02/04/2021 09:30:02,NaN
32061,01/04/2021 01:02:33,01/04/2021,"SAP, hourly actual",1.5765,02/04/2021 09:30:02,NaN
32062,01/04/2021 00:19:04,01/04/2021,"SAP, hourly actual",1.5626,02/04/2021 09:30:02,NaN

In [ ]:
NG_SAP_Hourly_Clean.head()

,Data Created,Gas Day,Label,Value (£/MWh),Generated Time,Quality Indicator
0,01/04/2025 21:02:20,01/04/2025,"SAP, hourly actual",3.3795,02/04/2025 09:45:05,NaN
1,01/04/2025 20:05:34,01/04/2025,"SAP, hourly actual",3.3701,02/04/2025 09:45:05,NaN
2,01/04/2025 19:03:06,01/04/2025,"SAP, hourly actual",3.3656,02/04/2025 09:45:05,NaN
3,01/04/2025 18:02:11,01/04/2025,"SAP, hourly actual",3.3606,02/04/2025 09:45:05,NaN
4,01/04/2025 17:03:05,01/04/2025,"SAP, hourly actual",3.3574,02/04/2025 09:45:05,NaN

In [ ]:
NG_SAP_Hourly_Clean = NG_SAP_Hourly_Clean.iloc[:,:-2]
NG_SAP_Hourly_Clean

              Data Created     Gas Day               Label  Value (£/MWh)
0      01/04/2025 21:02:20  01/04/2025  SAP, hourly actual         3.3795
1      01/04/2025 20:05:34  01/04/2025  SAP, hourly actual         3.3701
2      01/04/2025 19:03:06  01/04/2025  SAP, hourly actual         3.3656
3      01/04/2025 18:02:11  01/04/2025  SAP, hourly actual         3.3606
4      01/04/2025 17:03:05  01/04/2025  SAP, hourly actual         3.3574
...                    ...         ...                 ...            ...
32058  01/04/2021 05:06:13  01/04/2021  SAP, hourly actual         1.6532
32059  01/04/2021 04:02:38  01/04/2021  SAP, hourly actual         1.6532
32060  01/04/2021 02:01:18  01/04/2021  SAP, hourly actual         1.6532
32061  01/04/2021 01:02:33  01/04/2021  SAP, hourly actual         1.5765
32062  01/04/2021 00:19:04  01/04/2021  SAP, hourly actual         1.5626

[32063 rows x 4 columns]

In [ ]:
NG_SAP_Hourly_Clean['Value (£/MWh)'] = NG_SAP_Hourly_Clean['Value (£/MWh)']*10
NG_SAP_Hourly_Clean

              Data Created     Gas Day               Label  Value (£/MWh)
0      01/04/2025 21:02:20  01/04/2025  SAP, hourly actual         33.795
1      01/04/2025 20:05:34  01/04/2025  SAP, hourly actual         33.701
2      01/04/2025 19:03:06  01/04/2025  SAP, hourly actual         33.656
3      01/04/2025 18:02:11  01/04/2025  SAP, hourly actual         33.606
4      01/04/2025 17:03:05  01/04/2025  SAP, hourly actual         33.574
...                    ...         ...                 ...            ...
32058  01/04/2021 05:06:13  01/04/2021  SAP, hourly actual         16.532
32059  01/04/2021 04:02:38  01/04/2021  SAP, hourly actual         16.532
32060  01/04/2021 02:01:18  01/04/2021  SAP, hourly actual         16.532
32061  01/04/2021 01:02:33  01/04/2021  SAP, hourly actual         15.765
32062  01/04/2021 00:19:04  01/04/2021  SAP, hourly actual         15.626

[32063 rows x 4 columns]

In [ ]:
#spltting up date and time column
def split_datetime_column(df, column_name):
    df = df.copy()

    df['Date'] = df[column_name].str.split(' ').str[0]
    df['Time'] = df[column_name].str.split(' ').str[1]

    return df

NG_SAP_Hourly_processed = split_datetime_column(
    NG_SAP_Hourly_Clean,
    'Data Created')

NG_SAP_Hourly_Clean_processed

,Data Created,Gas Day,Label,Value (£/MWh),Date,Time
0,01/04/2025 21:02:20,01/04/2025,"SAP, hourly actual",33.795,01/04/2025,21:02:20
1,01/04/2025 20:05:34,01/04/2025,"SAP, hourly actual",33.701,01/04/2025,20:05:34
2,01/04/2025 19:03:06,01/04/2025,"SAP, hourly actual",33.656,01/04/2025,19:03:06
3,01/04/2025 18:02:11,01/04/2025,"SAP, hourly actual",33.606,01/04/2025,18:02:11
4,01/04/2025 17:03:05,01/04/2025,"SAP, hourly actual",33.574,01/04/2025,17:03:05
...,...,...,...,...,...,...
32058,01/04/2021 05:06:13,01/04/2021,"SAP, hourly actual",16.532,01/04/2021,05:06:13
32059,01/04/2021 04:02:38,01/04/2021,"SAP, hourly actual",16.532,01/04/2021,04:02:38
32060,01/04/2021 02:01:18,01/04/2021,"SAP, hourly actual",16.532,01/04/2021,02:01:18
32061,01/04/2021 01:02:33,01/04/2021,"SAP, hourly actual",15.765,01/04/2021,01:02:33
32062,01/04/2021 00:19:04,01/04/2021,"SAP, hourly actual",15.626,01/04/2021,00:19:04

In [ ]:
adj_columns = ['Date', 'Time', 'Label', 'Value (£/MWh)']
NG_SAP_Hourly_adj = NG_SAP_Hourly_Clean_processed[adj_columns].copy()
NG_SAP_Hourly_adj

             Date      Time               Label  Value (£/MWh)
0      01/04/2025  21:02:20  SAP, hourly actual         33.795
1      01/04/2025  20:05:34  SAP, hourly actual         33.701
2      01/04/2025  19:03:06  SAP, hourly actual         33.656
3      01/04/2025  18:02:11  SAP, hourly actual         33.606
4      01/04/2025  17:03:05  SAP, hourly actual         33.574
...           ...       ...                 ...            ...
32058  01/04/2021  05:06:13  SAP, hourly actual         16.532
32059  01/04/2021  04:02:38  SAP, hourly actual         16.532
32060  01/04/2021  02:01:18  SAP, hourly actual         16.532
32061  01/04/2021  01:02:33  SAP, hourly actual         15.765
32062  01/04/2021  00:19:04  SAP, hourly actual         15.626

[32063 rows x 4 columns]

In [ ]:
#convert to datetime object
NG_SAP_Hourly_adj['Date'] = pd.to_datetime(NG_SAP_Hourly_adj['Date'], format='%d/%m/%Y')

#adjustformat to be by YYYY_MM_DD
NG_SAP_Hourly_adj['Date'] = NG_SAP_Hourly_adj['Date'].dt.strftime('%Y-%m-%d')

NG_SAP_Hourly_adj

             Date      Time               Label  Value (£/MWh)
0      2025-04-01  21:02:20  SAP, hourly actual         33.795
1      2025-04-01  20:05:34  SAP, hourly actual         33.701
2      2025-04-01  19:03:06  SAP, hourly actual         33.656
3      2025-04-01  18:02:11  SAP, hourly actual         33.606
4      2025-04-01  17:03:05  SAP, hourly actual         33.574
...           ...       ...                 ...            ...
32058  2021-04-01  05:06:13  SAP, hourly actual         16.532
32059  2021-04-01  04:02:38  SAP, hourly actual         16.532
32060  2021-04-01  02:01:18  SAP, hourly actual         16.532
32061  2021-04-01  01:02:33  SAP, hourly actual         15.765
32062  2021-04-01  00:19:04  SAP, hourly actual         15.626

[32063 rows x 4 columns]

In [ ]:
# need to recombine date and time to round the time to nearest hour
NG_SAP_Hourly_adj['Datetime_Full'] = pd.to_datetime(
    NG_SAP_Hourly_adj['Date'] + ' ' + NG_SAP_Hourly_adj['Time'])

NG_SAP_Hourly_adj['Time_Rounded'] = NG_SAP_Hourly_adj['Datetime_Full'].dt.round('h')

# 3. Display the first few rows to confirm the result
NG_SAP_Hourly_adj

,Date,Time,Label,Value (£/MWh),Datetime_Full,Time_Rounded
0,2025-04-01,21:02:20,"SAP, hourly actual",33.795,2025-04-01 21:02:20,2025-04-01 21:00:00
1,2025-04-01,20:05:34,"SAP, hourly actual",33.701,2025-04-01 20:05:34,2025-04-01 20:00:00
2,2025-04-01,19:03:06,"SAP, hourly actual",33.656,2025-04-01 19:03:06,2025-04-01 19:00:00
3,2025-04-01,18:02:11,"SAP, hourly actual",33.606,2025-04-01 18:02:11,2025-04-01 18:00:00
4,2025-04-01,17:03:05,"SAP, hourly actual",33.574,2025-04-01 17:03:05,2025-04-01 17:00:00
...,...,...,...,...,...,...
32058,2021-04-01,05:06:13,"SAP, hourly actual",16.532,2021-04-01 05:06:13,2021-04-01 05:00:00
32059,2021-04-01,04:02:38,"SAP, hourly actual",16.532,2021-04-01 04:02:38,2021-04-01 04:00:00
32060,2021-04-01,02:01:18,"SAP, hourly actual",16.532,2021-04-01 02:01:18,2021-04-01 02:00:00
32061,2021-04-01,01:02:33,"SAP, hourly actual",15.765,2021-04-01 01:02:33,2021-04-01 01:00:00
32062,2021-04-01,00:19:04,"SAP, hourly actual",15.626,2021-04-01 00:19:04,2021-04-01 00:00:00

In [ ]:
new_columns = ['Time_Rounded', 'Label', 'Value (£/MWh)']
NG_SAP_Hourly_adj2 = NG_SAP_Hourly_adj[new_columns].copy()
NG_SAP_Hourly_adj2

             Time_Rounded               Label  Value (£/MWh)
0     2025-04-01 21:00:00  SAP, hourly actual         33.795
1     2025-04-01 20:00:00  SAP, hourly actual         33.701
2     2025-04-01 19:00:00  SAP, hourly actual         33.656
3     2025-04-01 18:00:00  SAP, hourly actual         33.606
4     2025-04-01 17:00:00  SAP, hourly actual         33.574
...                   ...                 ...            ...
32058 2021-04-01 05:00:00  SAP, hourly actual         16.532
32059 2021-04-01 04:00:00  SAP, hourly actual         16.532
32060 2021-04-01 02:00:00  SAP, hourly actual         16.532
32061 2021-04-01 01:00:00  SAP, hourly actual         15.765
32062 2021-04-01 00:00:00  SAP, hourly actual         15.626

[32063 rows x 3 columns]

In [ ]:
#if there were duplicates because of when hourly readings were taken, cleans them and takes mean based on Value column
NG_SAP_Hourly_adj2 = NG_SAP_Hourly_adj2.groupby('Time_Rounded')['Value (£/MWh)'].mean().reset_index()

# set index
NG_SAP_Hourly_adj2 = NG_SAP_Hourly_adj2.set_index('Time_Rounded')

#set data to 30-minute intervals
NG_SAP_Hourly_resampled = NG_SAP_Hourly_adj2.reindex(
    pd.date_range(
        start=NG_SAP_Hourly_adj2.index.min(),
        end=NG_SAP_Hourly_adj2.index.max(),
        freq='30min'))

# 4. Fill the new NaN rows (the half-hour points) with the last known value
NG_SAP_Hourly_resampled['Value (£/MWh)'] = NG_SAP_Hourly_resampled['Value (£/MWh)'].ffill()

NG_SAP_Hourly_resampled = NG_SAP_Hourly_resampled.rename_axis('Date_Time')
# Display the result
NG_SAP_Hourly_resampled

                     Value (£/MWh)
Date_Time
2021-04-01 00:00:00         15.626
2021-04-01 00:30:00         15.626
2021-04-01 01:00:00         15.765
2021-04-01 01:30:00         15.765
2021-04-01 02:00:00         16.532
...                            ...
2025-04-01 19:00:00         33.656
2025-04-01 19:30:00         33.656
2025-04-01 20:00:00         33.701
2025-04-01 20:30:00         33.701
2025-04-01 21:00:00         33.795

[70171 rows x 1 columns]

In [ ]:
NG_SAP_Hourly_resampled = NG_SAP_Hourly_resampled.rename(columns={'Value (£/MWh)':'Gas Price (£/MWh)'})
NG_SAP_Hourly_resampled

                     Gas Price (£/MWh)
Date_Time
2021-04-01 00:00:00             15.626
2021-04-01 00:30:00             15.626
2021-04-01 01:00:00             15.765
2021-04-01 01:30:00             15.765
2021-04-01 02:00:00             16.532
...                                ...
2025-04-01 19:00:00             33.656
2025-04-01 19:30:00             33.656
2025-04-01 20:00:00             33.701
2025-04-01 20:30:00             33.701
2025-04-01 21:00:00             33.795

[70171 rows x 1 columns]

In [ ]:
#just double checkign for duplicates
#with leapyear I think number of inputs should be 70,128
#mine includes most of 4/1 so I think that's why I"m over

is_duplicate = NG_SAP_Hourly_resampled.index.duplicated().any()
print(f"Are there any duplicate Date_Time entries? {is_duplicate}")

Are there any duplicate Date_Time entries? False

In [ ]:
#now I want to change time to settlement period

index_dt = NG_SAP_Hourly_resampled.index

#set up calc for SP:
#Calculate the total minutes past midnight (e.g., 01:30 is 90 minutes)
# Then divide by 30 minutes and add 1 to get the SP (1 to 48)
# Example: 00:00 is (0/30) + 1 = SP 1
# Example: 00:30 is (30/30) + 1 = SP 2
# Example: 23:30 is (1410/30) + 1 = SP 48
settlement_period = ((index_dt.hour * 60 + index_dt.minute) / 30).astype(int) + 1

#leading zero for SP
sp_formatted = pd.Series(settlement_period).astype(str).str.zfill(2).values
#format to add SP to date
date_part = index_dt.strftime('%Y-%m-%d')
new_index_values = date_part + '-' + sp_formatted

NG_SAP_Hourly_resampled.index = new_index_values

NG_SAP_Hourly_resampled

               Gas Price (£/MWh)
Date_Time
2021-04-01-01             15.626
2021-04-01-02             15.626
2021-04-01-03             15.765
2021-04-01-04             15.765
2021-04-01-05             16.532
...                          ...
2025-04-01-39             33.656
2025-04-01-40             33.656
2025-04-01-41             33.701
2025-04-01-42             33.701
2025-04-01-43             33.795

[70171 rows x 1 columns]

In [ ]:
Gas_Price_Final = NG_SAP_Hourly_resampled.rename_axis('Date_sp')

In [ ]:
Gas_Price_Final

               Gas Price (£/MWh)
Date_sp
2021-04-01-01             15.626
2021-04-01-02             15.626
2021-04-01-03             15.765
2021-04-01-04             15.765
2021-04-01-05             16.532
...                          ...
2025-04-01-39             33.656
2025-04-01-40             33.656
2025-04-01-41             33.701
2025-04-01-42             33.701
2025-04-01-43             33.795

[70171 rows x 1 columns]

In [ ]:
#Check for nulls

null_counts = Gas_Price_Final.isnull().sum()

print("--- Count of Null Values per Column ---")
print(null_counts)

--- Count of Null Values per Column ---
Gas Price (£/MWh)    0
dtype: int64

In [ ]:
Gas_Price_Final.index = Gas_Price_Final.index.astype('object')
Gas_Price_Final['Gas Price (£/MWh)'] = Gas_Price_Final['Gas Price (£/MWh)'].round(2)

print("--- Verified Data Type ---")
print(Gas_Price_Final.dtypes)

--- Verified Data Type ---
Gas Price (£/MWh)    float64
dtype: object

In [ ]:
Gas_Price_Final.to_csv(path_or_buf='/Users/leahmcgovern/BENV0091 Energy Data Analysis/Final Project/Datasets Clean/Gas_Prices_Clean.csv',
                       index=True,
                       header=True)